// Generated by view binder compiler. Do not edit!
package com.margareta.sahabatpena.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.ImageView;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.constraintlayout.widget.ConstraintLayout;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.margareta.sahabatpena.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class ActivityMain2Binding implements ViewBinding {
  @NonNull
  private final ConstraintLayout rootView;

  @NonNull
  public final ImageView imageView;

  @NonNull
  public final TextView teksDetailPengguna;

  @NonNull
  public final TextView teksSelamat;

  @NonNull
  public final Button tombolGithub;

  @NonNull
  public final Button tombolTentang;

  private ActivityMain2Binding(@NonNull ConstraintLayout rootView, @NonNull ImageView imageView,
      @NonNull TextView teksDetailPengguna, @NonNull TextView teksSelamat,
      @NonNull Button tombolGithub, @NonNull Button tombolTentang) {
    this.rootView = rootView;
    this.imageView = imageView;
    this.teksDetailPengguna = teksDetailPengguna;
    this.teksSelamat = teksSelamat;
    this.tombolGithub = tombolGithub;
    this.tombolTentang = tombolTentang;
  }

  @Override
  @NonNull
  public ConstraintLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static ActivityMain2Binding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ActivityMain2Binding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.activity_main2, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ActivityMain2Binding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.imageView;
      ImageView imageView = ViewBindings.findChildViewById(rootView, id);
      if (imageView == null) {
        break missingId;
      }

      id = R.id.teksDetailPengguna;
      TextView teksDetailPengguna = ViewBindings.findChildViewById(rootView, id);
      if (teksDetailPengguna == null) {
        break missingId;
      }

      id = R.id.teksSelamat;
      TextView teksSelamat = ViewBindings.findChildViewById(rootView, id);
      if (teksSelamat == null) {
        break missingId;
      }

      id = R.id.tombolGithub;
      Button tombolGithub = ViewBindings.findChildViewById(rootView, id);
      if (tombolGithub == null) {
        break missingId;
      }

      id = R.id.tombolTentang;
      Button tombolTentang = ViewBindings.findChildViewById(rootView, id);
      if (tombolTentang == null) {
        break missingId;
      }

      return new ActivityMain2Binding((ConstraintLayout) rootView, imageView, teksDetailPengguna,
          teksSelamat, tombolGithub, tombolTentang);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
