// Generated by view binder compiler. Do not edit!
package com.margareta.sahabatpena.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.ImageView;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.constraintlayout.widget.ConstraintLayout;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.margareta.sahabatpena.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class ActivityPenggunaBinding implements ViewBinding {
  @NonNull
  private final ConstraintLayout rootView;

  @NonNull
  public final ImageView gambarCepen;

  @NonNull
  public final ImageView gambarPuisi;

  @NonNull
  public final ImageView gambarQuotes;

  @NonNull
  public final TextView textView2;

  @NonNull
  public final Button tombolCerpen;

  @NonNull
  public final Button tombolPuisi;

  @NonNull
  public final Button tombolQuotes;

  private ActivityPenggunaBinding(@NonNull ConstraintLayout rootView,
      @NonNull ImageView gambarCepen, @NonNull ImageView gambarPuisi,
      @NonNull ImageView gambarQuotes, @NonNull TextView textView2, @NonNull Button tombolCerpen,
      @NonNull Button tombolPuisi, @NonNull Button tombolQuotes) {
    this.rootView = rootView;
    this.gambarCepen = gambarCepen;
    this.gambarPuisi = gambarPuisi;
    this.gambarQuotes = gambarQuotes;
    this.textView2 = textView2;
    this.tombolCerpen = tombolCerpen;
    this.tombolPuisi = tombolPuisi;
    this.tombolQuotes = tombolQuotes;
  }

  @Override
  @NonNull
  public ConstraintLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static ActivityPenggunaBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ActivityPenggunaBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.activity_pengguna, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ActivityPenggunaBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.gambarCepen;
      ImageView gambarCepen = ViewBindings.findChildViewById(rootView, id);
      if (gambarCepen == null) {
        break missingId;
      }

      id = R.id.gambarPuisi;
      ImageView gambarPuisi = ViewBindings.findChildViewById(rootView, id);
      if (gambarPuisi == null) {
        break missingId;
      }

      id = R.id.gambarQuotes;
      ImageView gambarQuotes = ViewBindings.findChildViewById(rootView, id);
      if (gambarQuotes == null) {
        break missingId;
      }

      id = R.id.textView2;
      TextView textView2 = ViewBindings.findChildViewById(rootView, id);
      if (textView2 == null) {
        break missingId;
      }

      id = R.id.tombolCerpen;
      Button tombolCerpen = ViewBindings.findChildViewById(rootView, id);
      if (tombolCerpen == null) {
        break missingId;
      }

      id = R.id.tombolPuisi;
      Button tombolPuisi = ViewBindings.findChildViewById(rootView, id);
      if (tombolPuisi == null) {
        break missingId;
      }

      id = R.id.tombolQuotes;
      Button tombolQuotes = ViewBindings.findChildViewById(rootView, id);
      if (tombolQuotes == null) {
        break missingId;
      }

      return new ActivityPenggunaBinding((ConstraintLayout) rootView, gambarCepen, gambarPuisi,
          gambarQuotes, textView2, tombolCerpen, tombolPuisi, tombolQuotes);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
