// Generated by view binder compiler. Do not edit!
package com.margareta.sahabatpena.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.EditText;
import android.widget.ImageView;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.constraintlayout.widget.ConstraintLayout;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.margareta.sahabatpena.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class ActivityMainBinding implements ViewBinding {
  @NonNull
  private final ConstraintLayout rootView;

  @NonNull
  public final ImageView gambarPena;

  @NonNull
  public final TextView helloSahabat;

  @NonNull
  public final EditText teksPassword;

  @NonNull
  public final EditText teksPengguna;

  @NonNull
  public final Button tombolLogin;

  private ActivityMainBinding(@NonNull ConstraintLayout rootView, @NonNull ImageView gambarPena,
      @NonNull TextView helloSahabat, @NonNull EditText teksPassword,
      @NonNull EditText teksPengguna, @NonNull Button tombolLogin) {
    this.rootView = rootView;
    this.gambarPena = gambarPena;
    this.helloSahabat = helloSahabat;
    this.teksPassword = teksPassword;
    this.teksPengguna = teksPengguna;
    this.tombolLogin = tombolLogin;
  }

  @Override
  @NonNull
  public ConstraintLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static ActivityMainBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ActivityMainBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.activity_main, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ActivityMainBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.gambarPena;
      ImageView gambarPena = ViewBindings.findChildViewById(rootView, id);
      if (gambarPena == null) {
        break missingId;
      }

      id = R.id.helloSahabat;
      TextView helloSahabat = ViewBindings.findChildViewById(rootView, id);
      if (helloSahabat == null) {
        break missingId;
      }

      id = R.id.teksPassword;
      EditText teksPassword = ViewBindings.findChildViewById(rootView, id);
      if (teksPassword == null) {
        break missingId;
      }

      id = R.id.teksPengguna;
      EditText teksPengguna = ViewBindings.findChildViewById(rootView, id);
      if (teksPengguna == null) {
        break missingId;
      }

      id = R.id.tombolLogin;
      Button tombolLogin = ViewBindings.findChildViewById(rootView, id);
      if (tombolLogin == null) {
        break missingId;
      }

      return new ActivityMainBinding((ConstraintLayout) rootView, gambarPena, helloSahabat,
          teksPassword, teksPengguna, tombolLogin);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
